cdklabs/publib

README.md
*Description of changes:*
updated README to change the release commands from 'jsii-release-*' into 'npx jsii-release-*'
Not sure if this is just me/my CircleCI setup, but I was getting `command not found` on the `jsii-release-*` commands (as can be seen [here](https://app.circleci.com/jobs/github/kollavarsham/kollavarsham-js/43)).
Changing the commands to `npx jsii-release-*` [helped](https://app.circleci.com/jobs/github/kollavarsham/kollavarsham-js/48/parallel-runs/0/steps/0-106) resolve this issue.
------
=> updated README to change the release commands

bin/jsii-release-npm
fix(jsii-release-npm): support publishing to AWS CodeArtifact NPM repository
Closes #3 
The NPM registry from AWS CodeArtifact comes with a trailing /, which creates the value of `NPM_REGISTRY` with double slash in .npmrc. This PR strips off the additional slash to make it work with AWS CodeArtifact.
=> fix(jsii-release-npm): support publishing to AWS CodeArtifact NPM repository

bin/jsii-release-maven
When multiple `*.pom` files exist under `dist/java`, i.e there are multiple packages to publish, the script does not iterate over all files and actually produces a single corrupted command.
Example:
```console
mvn --settings=/tmp/tmp.qeJue3YKgn/mvn-settings.xml gpg:sign-and-deploy-file -Durl=file:///tmp/tmp.FWzIxZoO74 -DrepositoryId=maven-central -Dgpg.homedir=/tmp/tmp.6ZGZGUow9z -Dgpg.keyname=0x28A12317239E021D -Dgpg.passphrase=*** -DpomFile=./org/***/***/0.25.0/***-0.25.0.pom ./org/***/***-plus/0.25.0/***-plus-0.25.0.pom -Dfile=./org/***/***/0.25.0/***-0.25.0.jar ./org/***/***-plus/0.25.0/***-plus-0.25.0.pom -Dsources=./org/***/***/0.25.0/***-0.25.0-sources.jar ./org/***/***-plus/0.25.0/***-plus-0.25.0.pom -Djavadoc=./org/***/***/0.25.0/***-0.25.0-javadoc.jar …
```
=> fix: dont quote list variable

bin/jsii-release-nuget
The `*` in the query is subject to bash expansion which messes up the invocation. 
```console
find: paths must precede expression: Org.Cdk8s.Plus.0.25.0.nupkg
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
##[error]Process completed with exit code 1.
```
Quote the query so that it doesn't undergo expansion.
=> fix: quote query in find command

README.md
*Description of changes:*
Twine supports [setting the PyPI combatible repository URL via environment variable](https://twine.readthedocs.io/en/latest/#commands). This PR adds documentation section about `TWINE_REPOSITORY_URL` into `README.md` within the `PyPI`-section.
I have verified that this works in my Github Action workflow that deploys to AWS CodeArtifact:
I have also verified that the uploaded artifact is available in AWS CodeArtifact:
=> Document optional TWINE_REPOSITORY_URL

README.md, bin/gpg-workaround.sh, bin/jsii-release-maven
Closes #11
- These restructures the maven release script to support non-nexus based repositories. In particular, a parallel execution path exists that simply uses the maven deploy plugin.
- At this particular time, signing is only supported for nexus repositories.
- The username, password, and gpg passphrase are also kept out of files and replaced with environment variable lookups.
- Did a bit of cleanup on error handling to route all single line errors through the `error` function
=> feat(maven): GitHub packages support

bin/jsii-release-maven
A previous commit forgot to remove the relevant line from the maven release script 
=> fix: maven release is broken

bin/jsii-release-maven
Deploying maven artifacts to sources other than maven central (i.e. github) was resulting in incorrect artifacts.
I believe that despite using `deploy`, a build was being down with just some metadata.
Now it uses `deploy-file` and explicitly specifies all artifacts. I've done a test run all the way through using the artifacts in a different project with success.
=> fix: Incorrect artifacts deployed for non maven central

README.md, bin/jsii-release-nuget
Two changes required.
1. Configurable `nuget_source` through `NUGET_SERVER` env var. Defaults to nuget.org
2. ~~Use `--skip-duplicate` option. Could also add additional error string checks, but seems better to use built-in support for ignoring conflicts.~~ Expand existing conflict check to work for GitHub. `skip-duplicate` seemed to work on nuget.org for the main package, but didn't work correctly for the symbols package.
I have tested new and conflict states on GitHub and nuget.org. Also using the package in a project.
=> feat(NuGet): Support NuGet GitHub Packages

bin/jsii-release-golang
`GIT_USER_NAME` may contain spaces, so it needs to be quoted. Currently it just uses the first word.
=> fix(golang): Username not fully respected if contains spaces

README.md, bin/jsii-release-golang
Added a module prefix to the tag. Either this, or a major version subdirectory is necessary for modules with a major version higher than `1` - we opted to use tag prefixes.
https://research.swtch.com/vgo-module#multiple-module_repositories 
This means that if a repository has multiple modules, it will have multiple tags for each version.
```console
===========================================
🏜️ DRY-RUN MODE 🏜️
===========================================
Cloning target repository aws/constructs-go
Cloning into '/var/folders/mb/5zx1h88x2891nhk4qpr6_zc8jcqzm6/T/tmp.Rzb5CmkP/repo'...
remote: Enumerating objects: 53, done.
remote: Total 53 (delta 0), reused 0 (delta 0), pack-reused 53
Unpacking objects: 100% (53/53), done.
/var/folders/mb/5zx1h88x2891nhk4qpr6_zc8jcqzm6/T/tmp.Rzb5CmkP/repo …
```
=> fix(golang): Repository are incorrectly tagged

bin/jsii-release-maven
Increase `stagingProgressTimeoutMinutes` from the default 5min to 10min since we are seeing quite a lot of timeouts deploying to maven central.
Fixes #29
=> fix(maven): maven central timeouts

src/targets/go.ts
The check was mixed up and caused confusing error messages.
=> fix: Input check should match error message

README.md, bin/jsii-release-maven
The `--gen-key` command of gpg has changed and now, in order to select options, users should use `--full-generate-key`.
=> fix: gpg keygen instructions are not accurate

src/help/git.ts, test/targets/go.test.ts
When trying to release to a non-default branch, Go releases fail because during checkout, jsii-release tries to run `git checkout -B <branch>` (so that it creates the branch if it doesn't exist). The problem is that if the branch does exist in the remote but it is not the default, git creates the branch at origin/HEAD instead of at origin/<branch>.
To fix this we check if the branch exists in the remote, and if so just run "git checkout" without -b (which will automatically track the correct branch).
Example failure run: https://github.com/cdk8s-team/cdk8s-plus/runs/3657009630?check_suite_focus=true#step:4:40
=> fix: go releases failing on non-default branches

.projen/tasks.json, .projenrc.js, package.json, yarn.lock
A recent feature to projen (projen/projen#1201) changed
the way that build tasks work. This breaks the upgrade workflow for this (and
several other projects).
=> chore: fix projen config after breaking change to build tasks

bin/jsii-release-npm
After assuming role the credentials needed to be exported to the environment for AWS CLI to pick and make the requests
Previosly the Access Key ad Secret Key were OK as they are in environment variables, and the code was overriding those. But the session token did not exist as environment variable hence not getting set.
Co-authored-by: Charlie Hart <charlie.hart@mondo.com.au>
Co-authored-by: Bibi Hagan <Bibi.Hagan@mondo.com.au>
=> fix(code Artifact): Fixed assume role to have new AWS creds as exported env variables

bin/jsii-release-shim
When executing publib through the `jsii-release` shim, the command line arguments are dropped.
When executed as follows:
```
jsii-release jsii-release-golang go/
```
It drops the `"go/"` argument, and proceeds to look at the default directory `dist/go` (which then causes an error).
Fixes #
=> fix(jsii-release-shim): command line arguments dropped

bin/publib-pypi
=> fix(pypi): Include verbose flag for twine upload

README.md, src/help/git.ts, test/targets/git.test.ts
Using git with a token might be simpler, but personal access tokens are very powerful. Using GitHub deploy keys will provide more fine grained control. If the secret is exposed, it will only affect that one specific repository. This will allow releasing go packages in projen without supplying a personal access token.
=> feat: Support cloning using SSH key

README.md, bin/publib-npm
Scoped npm packages cannot currently be published publicly because npm defaults to publishing them as [restricted](https://docs.npmjs.com/cli/v8/commands/npm-publish#access). This change gives the access level choice to the author.
=> feat(npm): support npm publishing with access level

.github/workflows/integ.yml, .projenrc.js
Mechanism:
We now have 2 otherwise identical environments, 'IntegTestCredentials' and 'IntegTestCredentialsRequireApproval', except one of them requires approvals to run.
A job will decide between them based on the submitter of the PR. If the submitter is a project member or our bot, we will pick the one that doesn't require approvals.
The output of this job is used as the value of the environment to use.
=> chore: only require deployment approval for 3P contributors

.github/workflows/integ.yml, .projenrc.ts
For some reason, @mrgrain is being marked as a `CONTRIBUTOR` (as opposed to a `MEMBER`) for this repository. This means he is not eligible for getting this PRs integ-tested without human approval.
@RomainMuller had the insight that we could simplify the check to saying "is the PR from a fork or not". Presumably people with write access are trusted, people who submit a forked PR are not.
Let's try it like this.
=> chore: "skip approval" check failing for some members

.github/workflows/integ.yml, .projenrc.ts, src/codeartifact/codeartifact-repo.ts
In SDKv3 they changed the error testing mechanism. It used to be `exc.code === '<error>'`, but now is `exc instanceof <error>`.
Fix that, and also update the documentation for the integ testing job.
Fixes #
=> fix(publib-ca): throttling errors are not retried

README.md, bin/publib-npm
This PR fixes 3 problems with NPM publishing
1. No support for other repositories (that use `_auth` instead of `_authToken`) e.g. Jfrog (closes #819)
2. No support for dry-run option, this is available in Go but not npm. (closes #820)
3. NPM publish will overwrite the users .npmrc, this has been switched out to use a temporary directory.
4. NPM publish did not clean up npmlog.txt on successful runs, this PR will cleanup the npmrc and log files.
---
Added two new options for `publib-npm`
- `NPM_DRYRUN` (optional): Set to "true" for a dry run
- `NPM_AUTH_TYPE` (optional): Can be "authToken" (default) or "auth" depending on the type of NPM_TOKEN used for the NPM_REGISTRY
=> feat(publib-npm): allow dry run and support `_auth` token type

README.md, bin/publib-npm
Reverts cdklabs/publib#821
This causes an error
```
npm WARN tarball tarball data for file:dist/js/**.tgz (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for file:dist/js/**.tgz (null) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /private/var/folders/_z/2dl7wtwd5xz42qh38n0fw0vw0000gr/T/tmp.IkuXtZo9/dist/js/**.tgz
```
=> chore: revert "feat(publib-npm): allow dry run and support `_auth` token type"

.github/workflows/integ.yml, .projenrc.ts
Between approval of the integ test deployment and the GH Actions runner picking up the job, the contents of the referenced branch could change because `pull_request.head.ref` is mutable. Using `sha` instead which is immutable.
This PR also updates the action versions for this workflow.
=> chore: fix integ test workflow to avoid possible race condition

.projen/deps.json, .projenrc.ts, package.json, tsconfig.dev.json, tsconfig.json, yarn.lock
`commit-and-tag-version@12` depends on a version of `lru-cache`, which fails typechecking of its definition files on modern TypeScript versions.
Disable lib checking to get the build to pass.
Undo the previous attempted fix which was to upgrade the version. It made the build pass but it broke `commit-and-tag-version` at runtime.
=> chore: disable type checking of libs

src/bin/publib-maven.ts
In the old bash version, we had the following command:
```sh
set -eu
some_function() {
export GPG_TTY=$(tty)
}
```
If there is no tty, this fails with exit code 1 but that doesn't stop the script if the failing subshell is part of an `export` command.
On GitHub Actions there is no tty which didn't stop the original script, but *does* stop the new script.
Configure `nothrow: true` on the `tty` subshell to avoid stopping the command.
=> fix(publib-maven): fails with "Subprocess failed with exit code 1"

src/bin/publib-maven.ts
A lot of the output of Maven looks like this:
```
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
Progress (2): 54 MB | 193/259 MB
```
Enable batch mode to disable progress reporting (according to Stack Overflow).
Fixes #
=> fix: disable progress display

README.md, bin/publib-nuget
Implements NuGet Trusted Publishing to enable secure, keyless publishing using GitHub Actions OIDC tokens instead of long-lived API keys.
Reference: https://learn.microsoft.com/en-us/nuget/nuget-org/trusted-publishing
- **Enhanced `publib-nuget`**: Added OIDC token exchange functionality
- Detects `NUGET_TRUSTED_PUBLISHER` environment variable
- Validates required `NUGET_USERNAME` for trusted publishing
- Exchanges GitHub OIDC token for temporary NuGet API key
- Maintains backward compatibility with existing `NUGET_API_KEY` workflow
- **Updated `README.md`**: Added comprehensive documentation
- New environment variables (`NUGET_TRUSTED_PUBLISHER`, `NUGET_USERNAME`)
- Trusted Publisher setup instructions
- GitHub Actions requirements (`id-token: write` permission)
- Eliminates need for …
=> feat(nuget): add trusted publisher support with OIDC authentication
